### ISSUE TITLE
More interpreter examples with memory, tables, etc.

### ISSUE THREAD

**Issue by NikVolf** [paritytech/parity-wasm#10]

**Comment by frehberg** [comment]
Writing a test for the interpreter (for example using WASM generated from C++), would it be fine for you if the WASM would be embedded (self containted)  as u8-array into the rs-test-file (plus  C++ and WAST aside in commented blocks)?

**Comment by NikVolf** [comment]
Sure, if the example will provide a little bit of utility when ready
otherwise, I would call it integration test

**Comment by NikVolf** [comment]
Interpretator departed to dedicated repo:
https://github.com/pepyakin/wasmi
