### ISSUE TITLE
It is unclear from the docs how to create a native module.

### ISSUE THREAD

**Issue by Kimundi** [paritytech/parity-wasm#126]
https://paritytech.github.io/parity-wasm/parity_wasm/interpreter/fn.native_module.html has a example for how to define a executor, but not for the steps needed to actually end up with a module that exports the functions it handles.

**Comment by pepyakin** [comment]
Yeah docs definitely could be better.
For now, you can take a look at [this test](https://github.com/paritytech/parity-wasm/blob/9895133048c55b2671d748ee716df69428a93587/src/interpreter/tests/basics.rs#L197) to see an example. If you feel brave enough you can also take a look [at the usage](https://github.com/paritytech/parity/blob/509038c9870bf8677c51ed413a10ae14178a8e35/ethcore/wasm/src/lib.rs) of parity-wasm in parity.

FWIW, at the moment we are working on overhaul of APIs incl. native modules.

**Comment by Kimundi** [comment]
Hm, still not entirely obvious from that example tbh. :)

I ended up implementing `ModuleInstanceInterface` manually for my first successful experiments, and wrote some macros for convient definitions of host functions. See the main function and two macros invocations at the end of https://gist.github.com/Kimundi/bb99fa6a682f752bf0a3980e5a4866bb.

**Comment by NikVolf** [comment]
Please refer to `wasmi` crate for new api and examples, interpreter dropped from here
