### ISSUE TITLE
module magic number assumes little-endian platform

### ISSUE THREAD

**Issue by icefoxen** [paritytech/parity-wasm#134]
In the definition of Default in module.rs the magic number is hard coded as a literal in little endian form, despite having it defined as a byte array right above.

**Comment by pepyakin** [comment]
@icefoxen Hi! Could you clarify why do you think this is a problem?

**Comment by icefoxen** [comment]
It probably won't work correctly when run on a big-endian platform?

Actually I'm not sure how wasm is defined to handle endianness, if at all.  Let me look into that.

**Comment by icefoxen** [comment]
Okay, looking at where the magic number is actually used, this only affects module loading.  But if you call `elements::Module::default()` on a big-endian platform (such as MIPS or PPC) then it will get an incorrect value for what it thinks the magic number should be, and will write a module with an incorrect magic number if you serialize it.

This is a one line fix, so I've submitted a PR.
