### ISSUE TITLE
Compact bytecode representation for interpreter

### ISSUE THREAD

**Issue by NikVolf** [paritytech/parity-wasm#135]
or other read-only purporses

**Comment by pepyakin** [comment]
Btw, we can go further by changing `Box<[u32]>` to something like [`thin-vec`](https://github.com/Gankro/thin-vec/blob/master/src/lib.rs#L188-L189): doing this will drop size of `Opcode` from 24 to 16!

**Comment by NikVolf** [comment]
Yeah I saw discussion in rust channel, the crate does not look very cool

I would prefer smth like custom enum which is pointer sized until it is mutated and then converts to just Vec (once mutated)

**Comment by pepyakin** [comment]
> the crate does not look very cool

yeah, I'm not insisting on using this particular `thin-vec` crate, but on the general idea of moving `size` part into the allocation itself.

> I would prefer smth like custom enum which is pointer sized until it is mutated and then converts to just Vec (once mutated)

But isn't this will require to this container to be the same size of `Box<[u32]>`?

**Comment by NikVolf** [comment]
Ah right, so it should be some smarter way to do the trick ;)

**Comment by pepyakin** [comment]
Closing this since interpreter is no longer in this repo. See  https://github.com/paritytech/wasmi/issues/100 for interpreter related tracking issue.
