### ISSUE TITLE
Disassembler?

### ISSUE THREAD

**Issue by icefoxen** [paritytech/parity-wasm#139]
Hi all,

I want to write a disassembler that turns compiled wasm back into wast code reversibly; I don't want to just use the official `wasm2wast` because I'm going to be integrating it into a Rust program.

I'm going to be using your serialization and deserialization routines and types no matter what, so, do you want me to write it as part of this crate and PR it back to you, or should I just make it a separate crate?

Thanks.

**Comment by NikVolf** [comment]
Hi!

I think separate crate is more logical solution to this, 
but it may be hosted in this repo, so that the ci is shared

You aware that `wast` is called `wat` now, right? :)

Will be happy to accept PR

**Comment by icefoxen** [comment]
All right, thanks!

...and yeah, but lots of things still call it `wast`, I suppose.  Oh well.

**Comment by pepyakin** [comment]
@icefoxen you might be interested in [wabt-rs](https://github.com/pepyakin/wabt-rs). It contains `wasm2wat` that might work for you.
