### ISSUE TITLE
current_memory and grow_memory instructions contain a bool?

### ISSUE THREAD

**Issue by icefoxen** [paritytech/parity-wasm#145]
The `CurrentMemory` and `GrowMemory` instructions have a `bool` as an argument.  The wasm spec states that they should be followed by a zero byte as a placeholder, but wouldn't it be easier to either omit it from the deserialized format, or use a `u8` or `i8`?

It's not a problem, since it's unused anyway, `bool` just seems like a weird choice... I'm not sure whether Rust actually specifies it to be a single byte.

Edit: `CallIndirect` has a similar structure.

**Comment by pepyakin** [comment]
@icefoxen definitely agree. I'm not sure why there `bool` and why it is read as `VarUint1`.

**Comment by NikVolf** [comment]
btw, not if that matter much, binary encoding specifies the argument of grow_memory and current_memory as `varuint1`, which is 1 bit in leb encoding, which in turn is 1 byte, but logically it is 1 or 0.

https://github.com/WebAssembly/design/blob/master/BinaryEncoding.md

It's just about how the boolean ended up there, no need to update anything

**Comment by pepyakin** [comment]
ah I see, so it lurked from https://github.com/WebAssembly/design/blob/master/BinaryEncoding.md

afaik the spec defines it is just 0x00 byte 
https://webassembly.github.io/spec/core/binary/instructions.html#memory-instructions

**Comment by pepyakin** [comment]
btw im not sure that we check that these immediates are equal to zero
