### ISSUE TITLE
Fuzzer found an error in deserialization (InvalidVarUint1(3))

### ISSUE THREAD

**Issue by pepyakin** [paritytech/parity-wasm#151]
Fuzzing with wasm-opt founds error `InvalidVarUint1(3)`

Here is base64 of this module

```AGFzbQEAAAABEgRgAAF/YAAAYAF9AX1gAXwBfAMFBAABAgMEBQFwAQAABQQBAwEBBgYBfwFBCgsHIQIGZnVuY18wAAAUaGFuZ0xpbWl0SW5pdGlhbGl6ZXIAAQkGAQBBAAsACvYBBMIBAAJAIwBFBEBBAQ8LIwBBAWskAAsCfwEDfwJAIwBFBEBBJA8LIwBBAWskAAtBx9y5owZBAUGAgH4EfwN/AkAjAEUEQEGSfw8LIwBBAWskAAtBgn8DfwJAIwBFBEBBuZx/DwsjAEEBayQACwJ/AkABAn8BDAELQQ9xA38CQCMARQRAQQEPCyMAQQFrJAALAn9BJAsLRQR/QZF/BUH//JF+C/4aARYLQfGcfkUNAUGAgIB8CwsNAwsFQYB/Cw0BDQELCwsGAEEKJAALEgAgACAAWwR9IAAFQwAAAAALCxYAIAAgAGEEfCAABUQAAAAAAAAAAAsLCwEA```

**Comment by NikVolf** [comment]
but it is invalid indeed?

**Comment by pepyakin** [comment]
I'm not sure ¯\_(ツ)_/¯ i didn't looked into this.

However, wabt/binaryen treat this module as a valid and parity-wasm report that error

**Comment by NikVolf** [comment]
Looks like wabt is wrong there

in this file, 3 is used for flags in resizable limits, which must be 0 or 1 at least according to:
https://github.com/WebAssembly/design/blob/master/BinaryEncoding.md

**Comment by NikVolf** [comment]
So, anyway, currently in wabt there is already support for memory flags, atomic operations opcodes that act only on shared memory.

Not sure it should be decoded until it hits binary encoding spec.
