### ISSUE TITLE
Fuzzer found an error in deserialization

### ISSUE THREAD

**Issue by pepyakin** [paritytech/parity-wasm#159]
base64 of a module
`AGFzbQEAAAABAAAABAQEBAQEBAQEBCoKBA0EBAQEBAQEBAQEBAQKCg==`

```
thread '<unnamed>' panicked at 'attempt to subtract with overflow', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-wasm-0.20.0/src/elements/section.rs:221:28
```

https://github.com/paritytech/parity-wasm/blob/a597cdb15d6d9a62c4e8856e9c884543449a18f5/src/elements/section.rs#L221

**Comment by NikVolf** [comment]
great, thanks

**Comment by NikVolf** [comment]
This is funny payload
With release optimizations it does not panic but leads to 4GB allocation
