### ISSUE TITLE
Common loader code for official test suite?

### ISSUE THREAD

**Issue by icefoxen** [paritytech/parity-wasm#160]
So for nanowasm's goal of [running the WebAssembly official test suite](https://github.com/icefoxen/nanowasm/issues/1) the easiest approach so far has been to do what parity-wasm is doing: run wabt's `wat2wasm` in the mode that builds a JSON specification of the tests to run, then load the JSON with serde.

In fact I just lifted parity-wasm's data structures directly, so that leads me to thinking: Would parity-wasm want to make those data structures part of the public API, perhaps under a feature flag?  Either that or factor them out into a separate crate that just does WebAssembly test suite loading, though that seems overkill.  Pro's: Easy code to reuse, obviously the need for reuse is there, and it does vaguely come under the goal of "serializing/deserializing WebAssembly stuff".  Might be possible to eventually evolve into loading the sexpr format to remove dependency on wat2wasm.  Con's: The wabt JSON format may change and parity-wasm's public API would have to change with it, or do what is done now and pin to a particular version of wabt and just let any downstream users deal with that.

Thoughts?  Ideas?  idk if this is at all interesting to you guys.  It'd just be marginally nice to not have to duplicate parity-wasm's data structures.

**Comment by pepyakin** [comment]
Good question! At the time, parity-wasm's interpreter is migrating in it's own repo: https://github.com/pepyakin/wasmi
We end up with just copying all spec project to this new repo.

I'm wondering, maybe we should move `spec` related thing to it's own create (even though in parity-wasm repo)?

@NikVolf what do you think?

**Comment by NikVolf** [comment]
Yeah, we can expose them, just as a separate crate

**Comment by NikVolf** [comment]
(in this repo)

**Comment by NikVolf** [comment]
I think it's already addressed in wasmi
