### ISSUE TITLE
Unique Identifier for every Element

### ISSUE THREAD

**Issue by s3bk** [paritytech/parity-wasm#190]
https://github.com/fitzgen/svelte relies on an unique identifier to create a graph. Right now the pointer of each element is used, which is not optimal.

Adding an unique identifier to each element during creation (via a global counter for example) would solve this. 

```rust
#[derive(Eq, Ord)]
pub struct Id(usize);

pub trait Unique {
    fn id(&self) -> Id;
}
```

**Comment by pepyakin** [comment]
Hi!

Personally, I think assigning IDs for the elements is job for a more high-level abstraction. You see, parity-wasm is more like low-level serialization-deserialization library, and tries to be more aligned with the wasm format (And wasm doesn't have any ids: it uses indicies to refer elements).

If @NikVolf agrees on this position, I think that we need to clarify it in docs and/or the description.

**Comment by s3bk** [comment]
closing as not really compatible with the parity-wasm design
