### ISSUE TITLE
GitHub version vs crates.io + sections mutable borrow API

### ISSUE THREAD

**Issue by lostman** [paritytech/parity-wasm#208]
The version on GitHub is
```
version = "0.27.5"
```
while the latest on crates.io:
```
parity-wasm = "0.27.6"
```
Does that include any code that's not on GitHub?

Also, are there plans to publish sections mutable borrow API https://github.com/paritytech/parity-wasm/commit/d1a74151e1cada759fdf6ae807ee54c10d6308b7 any time soon?

That would allow me to clean up a lot of code. I've been using latest `parity-wasm` from GitHub but would prefer to simply use a version from crates.io.

**Comment by NikVolf** [comment]
0.28 is out!
