### ISSUE TITLE
Make parity_wasm usable from no_std

### ISSUE THREAD

**Issue by pepyakin** [paritytech/parity-wasm#209]

**Comment by sorpaas** [comment]
Would like to help on this if that's okay. :)

**Comment by davidp94** [comment]
Is there any plan to run parity_wasm within a trusted execution environment in order to enable secret contracts?

**Comment by sorpaas** [comment]
Discussed with @pepyakin, going to work on `wasm-utils` no_std support instead. :)

**Comment by pepyakin** [comment]
@davidp94 Can you expand a little bit on what do you mean by "a trusted execution environment"?
