### ISSUE TITLE
There's no obvious way to control the Type Section when building modules

### ISSUE THREAD

**Issue by CryZe** [paritytech/parity-wasm#217]
I'm currently trying to use parity-wasm to generate some wasm, but it seems like I have absolutely no control over the type section. This is especially annoying since there's a billion duplicate types in there, meaning I can't use them with call_indirect. Most things related to function signatures aren't actually publicly exported and pushing a type section in myself emits it as the last section, which according to the spec is not allowed.

**Comment by pepyakin** [comment]
> I'm currently trying to use parity-wasm to generate some wasm, but it seems like I have absolutely no control over the type section.

> This is especially annoying since there's a billion duplicate types in there

That's mostly true. This comes from the fact that parity-wasm is rather a low-level serialization-deserialization library. Thus I wouldn't recommend using parity-wasm directly without additional abstractions. Although `parity_wasm::builder` might be more appropriate for your use-case. Have you tried it?

> meaning I can't use them with call_indirect

Sorry I think I don't follow here. Why this prevents you using `call_indirect`? Isn't `call_indirect` checks signatures structurally?

**Comment by CryZe** [comment]
I'm using parity_wasm::builder. That is what is generating the different type signatures for every single function you emit. For call_indirect you have to provide a type index, but I have way too many due to the builder generating too many. Unless call_indirect doesn't actually just check by index. I haven't actually checked the specs if that's the case. If not, then that would actually be fine then. However I'd say the ergonomics regarding control over the type section via the builder is still something to be improved as most types are just not publicly exported like the Signature type, and are thus practically unusable in the builder api.

**Comment by NikVolf** [comment]
@CryZe oh, i think it's easy to fix

will just reusing previously built signatures will be enough?
