### ISSUE TITLE
linear memory via mmap

### ISSUE THREAD

**Issue by frehberg** [paritytech/parity-wasm#228]
linear memory is located in virtual memory o process.
growing the linear memory may require to re-alloc complete array and copying from old to new, larger one.

Instead mmap should be used to reserve the virtual linear memory,  mapping it directly onto physical memory pages; this way linear could grow without re-alloc, but just mapping additional physical memory pages into the consecutive mmap-memory address space.

**Comment by NikVolf** [comment]
Hi, sure, this is the issue we have in `wasmi` interpreter!
https://github.com/paritytech/wasmi/issues/45
