### ISSUE TITLE
Name section is absent

### ISSUE THREAD

**Issue by RicoGit** [paritytech/parity-wasm#246]
### Problem
Name section in empty but should be present. 

### Step to reproduce
```shell 
cargo --version
      cargo 1.32.0-nightly (1fa308820 2018-10-31)
```
1. Compile this Rust code to wasm:
```rust
#[no_mangle]
pub unsafe fn outer_function(a: i32) -> i32 {
    inner_function(a)
}
#[inline(never)]
fn inner_function(a: i32) -> i32 {
    return if a % 2 == 0 { a + 111 } else { a }
}
```
like this:
```shell 
cargo  +nightly build --target wasm32-unknown-unknown --release
````
2. Read gotten wasm file with `parity-wasm` like this:
```rust
fn main() {
    let args = env::args().collect::<Vec<_>>();
    let module = parity_wasm::deserialize_file(&args[1]).unwrap();
    let name_sec = module.names_section();
    println!("{:?}", name_sec); // name section is None
}
```
Name section in `None` but should be present. 
If we convert wasm file to wast file like this:
```shell
wasm2wat app.wasm > app.wast
```
we will see the name of `inner_fuction`. This name keeps into the name section in the binary file. But this section isn't present in `parity-wasm`.

**Comment by NikVolf** [comment]
Hi!

By default, name section is not parsed and stays in custom sections as a blob

To parse it, use `parse_names` on loaded module
https://paritytech.github.io/parity-wasm/parity_wasm/elements/struct.Module.html#method.parse_names

So you code should look like this:

```
fn main() {
    let args = env::args().collect::<Vec<_>>();
    let module = parity_wasm::deserialize_file(&args[1]).unwrap().parse_names().unwrap();
    let name_sec = module.names_section();
    println!("{:?}", name_sec); // name section is None
}
```

**Comment by RicoGit** [comment]
Cool, thanks, it's my fault.
Docs let know about this.
