### ISSUE TITLE
Name section parsing

### ISSUE THREAD

**Issue by michaelvoronov** [paritytech/parity-wasm#268]
Hi!

As i understand correctly, It seems that parsing of name section is incomplete. According to the [spec](https://github.com/WebAssembly/design/blob/master/BinaryEncoding.md#name-section) it follow that: name section lies in custom section and it can has some (not one) subsections of three possible types (`ModuleNameSection`, `FunctionNameSection`, `LocalNameSection`). So pseudo-code for its deserialization could be as such:

<pre>
1. read custom header with name and size payload_len
2. while current_readed < payload_len:
  3. read name subsection with size name_payload_len
  4. current_readed += name_payload_len
</pre>

But now deserialization includes only 1 and 3 steps and parses only the first section. And [names_section](https://github.com/paritytech/parity-wasm/blob/ca99b786edc8fc7ebf39d0a698b86ebfb355532d/src/elements/module.rs#L331) returns not a sequence of subsections but just an enum that could be one of these subsection types. So if a module has all these three subsection types, it is possible to get only the first one (and also serialize only one).

**Comment by folex** [comment]
Btw, we already have a fix in [fluencelabs' fork of parity-wasm](https://github.com/fluencelabs/parity-wasm), you can see [diff here](https://github.com/paritytech/parity-wasm/compare/master...fluencelabs:master?expand=1). But we can't make tests pass by ourselves because there are some binary Wasm modules in tests that would deserialize only with a "broken" deserialization.

What's the best way to make this PR?

**Comment by folex** [comment]
Relevant discussion on matrix/riot: https://riot.im/app/#/room/#support:matrix.parity.io/$1553602603272264hzntW:matrix.org

**Comment by folex** [comment]
cc @svyatonik :)

**Comment by svyatonik** [comment]
I worked on interpreter mostly, so I'd ping @NikVolf here instead :) Nikolay, could you, please, take a look? :)

**Comment by svyatonik** [comment]
Think the reason is https://github.com/WebAssembly/design/pull/984
