### ISSUE TITLE
Multiple function results

### ISSUE THREAD

**Issue by g-r-a-n-t** [paritytech/parity-wasm#287]
WebAssembly text format supports multiple [function](https://webassembly.github.io/spec/core/text/types.html#abbreviations) results, this should be reflected here.

**Comment by nomeata** [comment]
This is essentially the multi-value proposal, as per https://github.com/WebAssembly/multi-value, which is already widely suppored, but still not official – so I guess it should live behind a feature flag?  Not sure what the policies in `parity-wasm` are for future proposals.

**Comment by g-r-a-n-t** [comment]
I see, a feature flag makes sense. Let me update the PR.
