### ISSUE TITLE
ModuleBuilder missing push_global function

### ISSUE THREAD

**Issue by bkolobara** [paritytech/parity-wasm#290]
I have noticed that [ModuleBuilder](https://docs.rs/parity-wasm/0.41.0/parity_wasm/builder/struct.ModuleBuilder.html) doesn't provide a convenience `push_global` function. This makes it really hard to reference the added global variable in further instructions.

Why is this one missing, but `push_function`, `push_memory`, `push_table` and others are provided?

**Comment by NikVolf** [comment]
I added it in #291 

Though if you generate complex wasm modules dynamically, better use https://github.com/nikvolf/wasm-graph (it handles linking naturally, without having to worry about indices)

**Comment by bkolobara** [comment]
Thanks @NikVolf for the really fast addition and the suggestion.

I just run into some indices related issues 😄. I will try wasm-graph, I wasn't aware of it before.
