### ISSUE TITLE
Multi-value block returns not implemented?

### ISSUE THREAD

**Issue by osa1** [paritytech/parity-wasm#292]
It seems like [multi-value extension][1] is currently only partially implemented, namely multi-value block returns [seems to be missing][2] (also confirmed by running the parser on [WebAssembly test suite][3]). Are there any plans on implementing full support for the multi-value extension?

I'd be happy to implement this myself if you're open to contributions. I think ~~making `BlockType` a newtype around `Vec<ValueType>` (similar to `results` field of `FunctionType`)~~ adding another variant to `BlockType` for the type index for multi-value returning blocks would work. This will be a breaking change so a major version bump will be required.

[1]: https://github.com/WebAssembly/multi-value/blob/master/proposals/multi-value/Overview.md
[2]: https://github.com/paritytech/parity-wasm/blob/23bf249139d678a66ae62f96639bfcd63fa1d46b/src/elements/types.rs#L98-L105
[3]: https://github.com/WebAssembly/testsuite

**Comment by NikVolf** [comment]
Sure, go ahead

just make sure that it is behind `multi_value` feature flag

**Comment by mackycheese21** [comment]
Any progress on this?
