### ISSUE TITLE
bufferred_read blows stack

### ISSUE THREAD

**Issue by stevemk14ebr** [paritytech/parity-wasm#320]
Hello, the routine here: https://github.com/paritytech/parity-wasm/blob/373f655f64d2260a2e9665811f7b6ed17f9db705/src/elements/mod.rs#L12

is often called with a size of about 0x4000. In embedded environments this can be over what's a reasonable stack size, and can cause the stack to blow. Even in a non-embedded environment this is a pretty big stack buffer, though it's not going to be an issue in usermode as there's usually a few MB of stack available.

This is currently hidden behind a crate flag reduced-stack-buffer to use a smaller default stack size. I suggest this be made the default. This flag is not being exposed in wasmi so users of that library cannot control this.

**Comment by stevemk14ebr** [comment]
https://github.com/paritytech/parity-wasm/pull/283 implemented the feature flag originally.

**Comment by athei** [comment]
We will merge https://github.com/paritytech/wasmi/pull/243

**Comment by stevemk14ebr** [comment]
That's very exciting thank you! Any chance of a release soon for this new feature flag. And in the future, potentially making these smaller values default?

**Comment by athei** [comment]
I will look into the wasmi release. However, won't be changing the default here as we don't want to risk any regressions.
