### ISSUE TITLE
Check the performance of resize()

### ISSUE THREAD

**Issue by NikVolf** [paritytech/parity-wasm#63]
This:
https://github.com/NikVolf/parity-wasm/commit/61f2ea770dc38075c70241bdc4eb6d71bc7bc9fd

is leading to performance degradation (at least in debug builds)

**Comment by Latrasis** [comment]
Hi! Not sure if this helps, but looks likely a remnant of: https://github.com/rust-lang/rust/issues/32155

**Comment by NikVolf** [comment]
Interpretator departed to dedicated repo:
https://github.com/pepyakin/wasmi
