### ISSUE TITLE
API for zero copy IO

### ISSUE THREAD

**Issue by frehberg** [paritytech/parity-wasm#97]
it should be possible to initialize interpreter with user defined u8-array-slice being used as environment memory by interpreter. This would enable parity-wasm to perform zero-copy IO in context of sockets.
API should provide helper functions to derive correct indices of elements being stored in the memory-chunk, such as length values, buffer-start/end, etc

**Comment by NikVolf** [comment]
I totally agree that interpreter should be able to execute code in the context of borrowed (mutably) memory, it is something we are thinking about at the moment.

Could you provide more details about 

> derive correct  indices of elements [...]

?
How can interpreter reason about those indices/length-es/buffers, etc. ?

**Comment by frehberg** [comment]
as for "derive correct indices of elements":

The assumption is that the parity-wasm interpreter can deal with single contiguous memory-chunk as env-memory. In this case its API should provide an abstract view onto this memory-chunk, exposing interfaces for partitioning and interpretation as primitive or length encoded array of variable length. As for the latter, length and capacity as structured prelude to the array-body.

parity-wasm should  provide a abstraction as simple memory manager in context of the contiguous memory-chunk, to deal with the corresponding allocation/partitioning and representation/marshalling of structured data. The abstract interface shall provide a native view as Rust-types (eg Rust array slices), but also exposing the index-positions of certain structured data instances encoded within the memory-chunk (prelude+body of array).

In case the interpreter would be able to deal with multiple memory-chunks (multiple array-slices) forming a virtual contiguous memory, the abstract interface should provide the logic to 'concat' these elements as linked list, and creating  a virtual index space. The abstract interface would create the corresponding indices for wasm-function invocation, and interpreter would need to map the index and offsets onto effective memory-chunks within the linked list.

I dont know which way parity-wasm intends to follow.

**Comment by NikVolf** [comment]
I am still thinking about the scope of this, and weather the scope is inside this library also.

Can you imagine example (code) of how it will be used?

**Comment by frehberg** [comment]
this is related to #96, the corresponding env-memory API.

Assuming we deal with a single linear memory chunk. The chunk  can be resizable, which means we are not allowed to deal with raw-references into that chunk, but just with indeces, that are transformed to rust-refs if required.

// => linear memory is created
// memory  may grow automatically
let env_memory = env_instance.memory(ItemIndex::Internal(0)).unwrap();
// append/alloc  memory for primitive  
let  idx : PrimIdx<i32> = env_memory.prim_alloc<i32>(); // index probably alligned to sizeof(i32)
let ar_idx : SeqIdx<&mut [u8]> = env_memory.seq_alloc(octet_size);  // no alignmend

// no more allocation must occure from now on, to prevent memory-chunk is resized and position of the
// memory is changing

idx.set(42); // demonstrating setting of primitive

let io_buffer : mut &[u8] = ar_idx.get();
let (nread, fromaddr) = socket.recv(io_buffer, octet_size);
...
The wasm functions would  be invoked with two parameters,  index of buffer and its octet-length.

it would be possible to place the complex structure of vec<u8> in the env-memory as well, but it would be necessary to standardize the memory layout, a canonical form between  Rusts Vec<>, Javascript-Arrays and C++ std::vector<>, etc.

**Comment by NikVolf** [comment]
Interpreter moved to `wasmi` crate
