### ISSUE TITLE
Configurable validation

### ISSUE THREAD

**Issue by NikVolf** [paritytech/parity-wasm#99]
Since validation does full code scan anyway, there should be an option to add custom validation steps (opcode-/function-/type- wise etc.)

For example, in blockchain applications any instructions that involve floating-point operations might be considered as invalid

**Comment by fckt** [comment]
moved to https://github.com/paritytech/wasm-utils/issues/17

**Comment by NikVolf** [comment]
Still I believe it might be useful on it's own

**Comment by pepyakin** [comment]
One use case is refining limits for an embedder. For example blockchain embeddings might want to constrain how much memory contract is allowed to use.

**Comment by NikVolf** [comment]
Interpretator departed to dedicated repo:
https://github.com/pepyakin/wasmi
